scene: data/nissan
logs_folder: logs/nissan
log_every: 1_000
image_scale: 0.5
train_image_log: 13

optimization:
  lr: 0.001
  n_iterations: 100_000
  n_rays: 4096

nerf:
  mlp:
    x_pos_dim: 10
    d_pos_dim: 4
    inner_dim: 256
    n_layers: 6
    conditioned_layers: [4]
  
  sampling_depth: 1.0
  n_coarse_samples: 64
  n_fine_samples: 128
